on:
  push:
    branches:
      - master

jobs:
  version:
    runs-on: ubuntu-latest
    env:
      MAJOR_VERSION: 1
    outputs:
      versionOut: ${{ steps.generateVersion.outputs.version }}
      versionSemVerOut: ${{ steps.semVer.outputs.semVersion }}
    steps:
      - id: generateVersion
        run: echo "version=$MAJOR_VERSION.0.${{ github.run_number }}.0" >> "$GITHUB_OUTPUT"
      - id: semVer
        run: echo "semVersion=$MAJOR_VERSION.0.${{ github.run_number }}" >> "$GITHUB_OUTPUT"
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs:
      - version
    env:
      TARGET_VERSION: ${{needs.version.outputs.versionOut}}
      SEM_VERSION: ${{needs.version.outputs.versionSemVerOut}}
    steps:
      - run: sudo apt-get update && sudo apt-get install -y jq
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Set version in manifest
        run: jq --arg ver "$TARGET_VERSION" '.Version = $ver' ./resources/manifest.json > temp.json && mv temp.json ./resources/manifest.json
      - run: docker build -t temp .
      - run: docker run --rm -v "$PWD/tmpdist:/tmpdist" temp sh -c "cp /dist/com.ftt.apimonkey.sdPlugin.zip /tmpdist/com.ftt.apimonkey.sdPlugin.zip"
      - name: release
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3.0.2
        with:
          draft: false
          prerelease: false
          name: ${{ env.TARGET_VERSION }}
          tag_name: ${{ env.SEM_VERSION }}
          files: tmpdist/com.ftt.apimonkey.sdPlugin.zip
          fail_on_unmatched_files: true
